name: Apple macOS
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - lane: oldest
            xcode: "15.4"
            deployment: "10.13"
          - lane: latest
            xcode: "latest-stable"
            deployment: "26.2"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: ./.github/actions/ensure-swift
        with:
          min-version: "6.2"
          target-version: "6.2"
      - run: xcodebuild -resolvePackageDependencies -scheme "Stheno"
      - run: xcodebuild test -scheme "Stheno" -destination "platform=macOS" MACOSX_DEPLOYMENT_TARGET=${{ matrix.deployment }}
