name: Apple watchOS
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

concurrency:
  group: ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/_apple-sim-tests.yml
    with:
      workflow-name: "watchOS"
      scheme: "Stheno"
      sim-runtime-prefix: "com.apple.CoreSimulator.SimRuntime.watchOS"
      device-name-regex: "Apple Watch"
      oldest-os: "5.0"
      latest-os: "26.2"
      xcode-old: "16.1"
      xcode-new: "latest-stable"
