name: Windows
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

env:
  SWIFT_MIN_VERSION: "6.2"
  SWIFT_TARGET_VERSION: "6.2"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2025]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ensure-swift
        with:
          min-version: ${{ env.SWIFT_MIN_VERSION }}
          target-version: ${{ env.SWIFT_TARGET_VERSION }}
      - shell: pwsh
        run: swift build -c release -v
      - shell: pwsh
        run: swift test -v
