name: Windows
on: { push: { branches: [main] }, pull_request: {}, workflow_dispatch: {} }

concurrency:
  group: ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2025]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ensure-swift
      - shell: pwsh
        run: swift build -c release -v
      - shell: pwsh
        run: swift test -v
